import {
  Proponent,
  Permit,
  ReportSchedule,
  Finding,
  EvidenceUpload,
  Booking,
  ServiceRequest,
  NotificationLog,
  CompanySetting,
  User,
} from '../types';

const STORAGE_KEY = 'aec_compliance_data_v2';

export interface StorageData {
  users: User[];
  proponents: Proponent[];
  permits: Permit[];
  schedules: ReportSchedule[];
  findings: Finding[];
  evidence: EvidenceUpload[];
  bookings: Booking[];
  requests: ServiceRequest[];
  logs: NotificationLog[];
  companySettings: CompanySetting;
}

const initialSeedData: StorageData = {
  users: [
    {
      id: 'user-admin-1',
      email: 'info@ansumana.com',
      full_name: 'Dr. Ansumana Kamara (AEC Admin)',
      role: 'admin',
      created_date: '2026-01-10T08:00:00.000Z',
    },
    {
      id: 'user-client-1',
      email: 'compliance@liberiagold.lr',
      full_name: 'Liberia Gold Mining Ltd. Compliance Officer',
      role: 'client',
      proponent_id: 'prop-1',
      created_date: '2026-02-01T10:00:00.000Z',
    },
    {
      id: 'user-client-2',
      email: 'env@monroviacoldstorage.lr',
      full_name: 'Monrovia Cold Storage Operations Manager',
      role: 'client',
      proponent_id: 'prop-2',
      created_date: '2026-02-15T12:00:00.000Z',
    },
  ],
  proponents: [
    {
      id: 'prop-1',
      company_name: 'Liberia Gold Mining Ltd.',
      contact_person: 'Mohamed Sesay',
      email: 'compliance@liberiagold.lr',
      phone: '+231 088 554 3210',
      whatsapp_number: '+231 077 554 3210',
      project_type: 'Gold mining',
      county: 'Nimba County',
      district: 'Sanniquellie District',
      project_location: 'Yekepa Mining Lease Area',
      project_description: 'Open-pit gold exploration and tailings processing facility.',
      status: 'Active',
      created_date: '2026-01-15T09:30:00.000Z',
    },
    {
      id: 'prop-2',
      company_name: 'Monrovia Cold Storage & Marine Logistics',
      contact_person: 'Fatu Bangura',
      email: 'env@monroviacoldstorage.lr',
      phone: '+231 088 112 3344',
      whatsapp_number: '+231 077 112 3344',
      project_type: 'Cold storage',
      county: 'Montserrado County',
      district: 'Freeport Area',
      project_location: 'Freeport of Monrovia Berth 3',
      project_description: 'Industrial ammonia refrigeration cold store and seafood export logistics hub.',
      status: 'Active',
      created_date: '2026-01-20T11:00:00.000Z',
    },
    {
      id: 'prop-3',
      company_name: 'Nimba Granite Quarry & Aggregate Resources',
      contact_person: 'Sahr Dumbuya',
      email: 'sdumbuya@nimbaaggregate.lr',
      phone: '+231 088 998 8770',
      whatsapp_number: '+231 077 998 8770',
      project_type: 'Mining and quarry',
      county: 'Nimba County',
      district: 'Ganta District',
      project_location: 'Ganta Highway Sector 4',
      project_description: 'Hard rock granite crushing plant producing road construction aggregates.',
      status: 'Active',
      created_date: '2026-02-05T14:15:00.000Z',
    },
    {
      id: 'prop-4',
      company_name: 'Ducor Luxury Resort & Eco-Lodge',
      contact_person: 'Amina Mansaray',
      email: 'management@ducor-ecolodge.lr',
      phone: '+231 088 443 2100',
      whatsapp_number: '+231 077 443 2100',
      project_type: 'Hotel',
      county: 'Montserrado County',
      district: 'Paynesville',
      project_location: '72nd SKD Boulevard Coastal Zone',
      project_description: 'Coastal eco-resort with wastewater treatment and solar hybrid microgrid.',
      status: 'Active',
      created_date: '2026-02-12T16:00:00.000Z',
    },
  ],
  permits: [
    {
      id: 'perm-101',
      proponent_id: 'prop-1',
      proponent_name: 'Liberia Gold Mining Ltd.',
      permit_number: 'EPA-LR-MIN-2025-089',
      permit_type: 'EPA Environmental Permit',
      issue_date: '2025-03-01',
      expiry_date: '2026-08-28',
      permit_status: 'Active',
      permit_file_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
      created_date: '2026-01-15T10:00:00.000Z',
    },
    {
      id: 'perm-102',
      proponent_id: 'prop-2',
      proponent_name: 'Monrovia Cold Storage & Marine Logistics',
      permit_number: 'EPA-LR-IND-2025-042',
      permit_type: 'EPA Environmental Permit',
      issue_date: '2025-09-15',
      expiry_date: '2026-09-14',
      permit_status: 'Active',
      permit_file_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
      created_date: '2026-01-20T11:30:00.000Z',
    },
    {
      id: 'perm-103',
      proponent_id: 'prop-3',
      proponent_name: 'Nimba Granite Quarry & Aggregate Resources',
      permit_number: 'EPA-LR-ML-2024-112',
      permit_type: 'Mining License',
      issue_date: '2024-08-10',
      expiry_date: '2026-08-15', // Expiry soon
      permit_status: 'Pending Renewal',
      permit_file_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
      created_date: '2026-02-05T14:30:00.000Z',
    },
    {
      id: 'perm-104',
      proponent_id: 'prop-4',
      proponent_name: 'Ducor Luxury Resort & Eco-Lodge',
      permit_number: 'EPA-LR-EIA-2025-201',
      permit_type: 'Environmental Impact License',
      issue_date: '2025-01-10',
      expiry_date: '2027-01-09',
      permit_status: 'Active',
      permit_file_url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
      created_date: '2026-02-12T16:30:00.000Z',
    },
  ],
  schedules: [
    {
      id: 'sched-1',
      proponent_id: 'prop-1',
      proponent_name: 'Liberia Gold Mining Ltd.',
      permit_id: 'perm-101',
      report_type: 'Biannual Monitoring Report',
      reporting_period: 'Q1-Q2 2026 Compliance Monitoring',
      due_date: '2026-08-25',
      status: 'Pending',
      reminder_30_sent: true,
      reminder_14_sent: true,
      reminder_7_sent: false,
      reminder_1_sent: false,
      reminder_due_sent: false,
      reminder_overdue_sent: false,
      created_date: '2026-01-15T11:00:00.000Z',
    },
    {
      id: 'sched-2',
      proponent_id: 'prop-2',
      proponent_name: 'Monrovia Cold Storage & Marine Logistics',
      permit_id: 'perm-102',
      report_type: 'Quarterly Monitoring Report',
      reporting_period: 'Q2 2026 Refrigerant Safety & Waste Audit',
      due_date: '2026-08-18',
      status: 'Pending',
      reminder_30_sent: true,
      reminder_14_sent: true,
      reminder_7_sent: true,
      reminder_1_sent: false,
      reminder_due_sent: false,
      reminder_overdue_sent: false,
      created_date: '2026-01-20T12:00:00.000Z',
    },
    {
      id: 'sched-3',
      proponent_id: 'prop-3',
      proponent_name: 'Nimba Granite Quarry & Aggregate Resources',
      permit_id: 'perm-103',
      report_type: 'Environmental Audit Report',
      reporting_period: 'Annual Reclamation & Dust Control Audit',
      due_date: '2026-08-01',
      status: 'Overdue',
      reminder_30_sent: true,
      reminder_14_sent: true,
      reminder_7_sent: true,
      reminder_1_sent: true,
      reminder_due_sent: true,
      reminder_overdue_sent: true,
      created_date: '2026-02-05T15:00:00.000Z',
    },
    {
      id: 'sched-4',
      proponent_id: 'prop-4',
      proponent_name: 'Ducor Luxury Resort & Eco-Lodge',
      permit_id: 'perm-104',
      report_type: 'Quarterly Monitoring Report',
      reporting_period: 'Q3 2026 Coastal Wastewater Discharge Monitoring',
      due_date: '2026-09-30',
      status: 'Pending',
      reminder_30_sent: false,
      reminder_14_sent: false,
      reminder_7_sent: false,
      reminder_1_sent: false,
      reminder_due_sent: false,
      reminder_overdue_sent: false,
      created_date: '2026-02-12T17:00:00.000Z',
    },
  ],
  findings: [
    {
      id: 'find-1',
      proponent_id: 'prop-1',
      proponent_name: 'Liberia Gold Mining Ltd.',
      report_schedule_id: 'sched-1',
      inspection_area: 'Tailings Retention Dam & Cyanide Storage Bay',
      finding_title: 'Inadequate Spill Containment Bunding around Reagent Tank',
      finding_description: 'The secondary containment bund wall at the cyanide leaching reagent shed exhibits 15cm cracks and incomplete masonry lining, posing run-off risks to local streams during torrential rains.',
      compliance_status: 'Major non-compliance',
      risk_level: 'High',
      corrective_action: 'Seal all structural cracks in secondary containment bund with epoxy mortar and apply chemical-resistant membrane sealant.',
      recommendation: 'Perform daily integrity checks and install automated secondary containment sump alarm.',
      action_deadline: '2026-08-20',
      responsible_party: 'Mine HSE Manager (Mohamed Sesay)',
      action_status: 'Submitted for review',
      sent_to_proponent: true,
      created_date: '2026-07-28T09:00:00.000Z',
    },
    {
      id: 'find-2',
      proponent_id: 'prop-1',
      proponent_name: 'Liberia Gold Mining Ltd.',
      report_schedule_id: 'sched-1',
      inspection_area: 'Artisanal Pits & Soil Reclamation Zone C',
      finding_title: 'Unvegetated Slope Soil Erosion near Drainage Trench',
      finding_description: 'Siltation observed in nearby stream discharge channel due to lack of vetiver grass turfing on freshly excavated overburden stock slopes.',
      compliance_status: 'Minor non-compliance',
      risk_level: 'Medium',
      corrective_action: 'Deploy sediment silt fences along slope base and initiate bio-engineering re-vegetation with fast-rooting local grass species.',
      recommendation: 'Construct sediment retention traps at 50-meter intervals.',
      action_deadline: '2026-08-30',
      responsible_party: 'Liberia Gold Site Civil Team',
      action_status: 'In progress',
      sent_to_proponent: true,
      created_date: '2026-07-28T09:30:00.000Z',
    },
    {
      id: 'find-3',
      proponent_id: 'prop-2',
      proponent_name: 'Monrovia Cold Storage & Marine Logistics',
      report_schedule_id: 'sched-2',
      inspection_area: 'Ammonia Compressor Room 2',
      finding_title: 'Expired Gas Detector Calibration Certificates',
      finding_description: 'Ammonia gas sensors installed in Compressor Room 2 passed expiration inspection dates in May 2026 without documented re-calibration.',
      compliance_status: 'Observation',
      risk_level: 'Low',
      corrective_action: 'Engage certified technician to re-calibrate gas sensors and upload updated calibration certificates to portal.',
      recommendation: 'Maintain a digital calibration logbook with automatic 30-day alerts.',
      action_deadline: '2026-08-22',
      responsible_party: 'Fatu Bangura (Maintenance Operations)',
      action_status: 'Pending',
      sent_to_proponent: true,
      created_date: '2026-08-01T10:00:00.000Z',
    },
    {
      id: 'find-4',
      proponent_id: 'prop-3',
      proponent_name: 'Nimba Granite Quarry & Aggregate Resources',
      report_schedule_id: 'sched-3',
      inspection_area: 'Primary Jaw Crusher & Haul Road Sector',
      finding_title: 'Uncontrolled Fugitive Dust Emissions during Crushing Operations',
      finding_description: 'Dust suppression water sprayers on the primary jaw crusher were found inactive, causing heavy airborne particulate pollution affecting nearby village settlements.',
      compliance_status: 'Major non-compliance',
      risk_level: 'High',
      corrective_action: 'Repair main water pressure pump, restore automated misting suppression system, and operate dedicated water bowser along haul roads hourly.',
      recommendation: 'Implement continuous PM10 air quality monitoring sensors.',
      action_deadline: '2026-08-10',
      responsible_party: 'Quarry Manager (Sahr Dumbuya)',
      action_status: 'Overdue',
      sent_to_proponent: true,
      created_date: '2026-07-15T11:00:00.000Z',
    },
  ],
  evidence: [
    {
      id: 'ev-1',
      finding_id: 'find-1',
      proponent_id: 'prop-1',
      file_url: 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b7?auto=format&fit=crop&w=800&q=80',
      file_name: 'Bund_Reinforcement_Mortar_Photos.pdf',
      file_type: 'image/jpeg',
      comment: 'Repaired bund wall with epoxy mortar, sealed all hairline fractures, and applied chemical membrane. Photos and material receipt attached.',
      date_action_completed: '2026-08-08',
      submitted_by: 'Mohamed Sesay (Mine HSE)',
      review_status: 'Pending review',
      created_date: '2026-08-08T14:20:00.000Z',
    },
  ],
  bookings: [
    {
      id: 'book-1',
      full_name: 'Mohamed Sesay',
      company_name: 'Liberia Gold Mining Ltd.',
      email: 'compliance@liberiagold.lr',
      phone: '+231 088 554 3210',
      whatsapp_number: '+231 077 554 3210',
      service_needed: 'Biannual monitoring planning session',
      preferred_date: '2026-08-16',
      preferred_time: '10:00 AM',
      project_location: 'Yekepa Site / AEC Paynesville Office',
      message: 'Requesting pre-audit review call with AEC environmental lead ahead of EPA Liberia inspection.',
      booking_status: 'Confirmed',
      meeting_link: 'https://meet.google.com/aec-lr-gold-2026',
      created_date: '2026-08-05T09:00:00.000Z',
    },
    {
      id: 'book-2',
      full_name: 'David Koroma',
      company_name: 'Sinoe Timber & Logging Co.',
      email: 'dkoroma@sinoetimber.lr',
      phone: '+231 088 331 1122',
      whatsapp_number: '+231 077 331 1122',
      service_needed: 'ESIA/EMP/EPB consultation',
      preferred_date: '2026-08-20',
      preferred_time: '02:00 PM',
      project_location: 'Sinoe Forestry Zone',
      message: 'Need advice on preparing Environmental Project Brief for new sustainable timber concession.',
      booking_status: 'Pending',
      created_date: '2026-08-10T11:45:00.000Z',
    },
  ],
  requests: [
    {
      id: 'req-1',
      full_name: 'Josephine Kamara',
      company_name: 'Atlantic Fish Freezing Plant',
      email: 'jkamara@atlanticfish.lr',
      phone: '+231 088 769 9900',
      whatsapp_number: '+231 077 769 9900',
      service_needed: 'Environmental Audit Report',
      project_location: 'Freeport Dockyard, Monrovia',
      message: 'We require a full annual EPA environmental audit report for our cold chain seafood processing factory.',
      status: 'New',
      created_date: '2026-08-09T16:10:00.000Z',
    },
    {
      id: 'req-2',
      full_name: 'Emmanuel Conteh',
      company_name: 'St. Paul River Sand Mining Association',
      email: 'econteh@stpaulsand.lr',
      phone: '+231 088 823 4567',
      whatsapp_number: '+231 077 823 4567',
      service_needed: 'Mining license support',
      project_location: 'Montserrado / St. Paul Riverbank',
      message: 'Seeking AEC compliance advisory to obtain EPA mining permit for organized riverbed sand extraction.',
      status: 'Contacted',
      created_date: '2026-08-02T13:20:00.000Z',
    },
  ],
  logs: [
    {
      id: 'log-1',
      proponent_id: 'prop-1',
      report_schedule_id: 'sched-1',
      channel: 'Email',
      notification_type: 'Report reminder',
      recipient: 'compliance@liberiagold.lr',
      subject: 'AEC Compliance Notice: Biannual Monitoring Report Due in 14 Days',
      message_body: 'Dear Mohamed Sesay, this is a reminder from Ansumana Environmental Consultancy Inc. Your Biannual Monitoring Report for Liberia Gold Mining Ltd. is due on 2026-08-25. Please contact AEC to arrange final monitoring submissions.',
      status: 'Sent',
      created_date: '2026-08-11T08:00:00.000Z',
    },
    {
      id: 'log-2',
      proponent_id: 'prop-1',
      report_schedule_id: 'sched-1',
      channel: 'WhatsApp',
      notification_type: 'Report reminder',
      recipient: '+231 077 554 3210',
      subject: 'WhatsApp Alert: Report Deadline Reminder',
      message_body: '[AEC Alert] Dear Mohamed Sesay, Biannual Monitoring Report for Liberia Gold Mining Ltd. is due on 2026-08-25. Log into AEC Portal to manage findings.',
      status: 'Sent',
      created_date: '2026-08-11T08:01:00.000Z',
    },
    {
      id: 'log-3',
      proponent_id: 'prop-3',
      report_schedule_id: 'sched-3',
      channel: 'Email',
      notification_type: 'Overdue notice',
      recipient: 'sdumbuya@nimbaaggregate.lr',
      subject: 'URGENT: Environmental Audit Report is OVERDUE - EPA Liberia Notice',
      message_body: 'Dear Sahr Dumbuya, your Environmental Audit Report due on 2026-08-01 is currently overdue. Please contact AEC immediately to avoid regulatory sanctions.',
      status: 'Sent',
      created_date: '2026-08-02T09:00:00.000Z',
    },
  ],
  companySettings: {
    id: 'setting-1',
    company_name: 'Ansumana Environmental Consultancy Inc. (AEC)',
    company_email: 'info@ansumana.com',
    company_phone: '+231 088 125 2254',
    company_whatsapp: '+231 077 530 1445',
    company_address: '72nd SKD Boulevard, Opposite Praise International Church Paynesville, Liberia',
    company_tagline: 'Precision Stewardship for a Sustainable Future',
    enable_email_notifications: true,
    enable_whatsapp_notifications: true,
    reminder_30_enabled: true,
    reminder_14_enabled: true,
    reminder_7_enabled: true,
    reminder_1_enabled: true,
  },
};

export function getStorageData(): StorageData {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(initialSeedData));
      return initialSeedData;
    }
    const parsed = JSON.parse(raw);
    // Ensure structure complete
    return {
      users: parsed.users || initialSeedData.users,
      proponents: parsed.proponents || initialSeedData.proponents,
      permits: parsed.permits || initialSeedData.permits,
      schedules: parsed.schedules || initialSeedData.schedules,
      findings: parsed.findings || initialSeedData.findings,
      evidence: parsed.evidence || initialSeedData.evidence,
      bookings: parsed.bookings || initialSeedData.bookings,
      requests: parsed.requests || initialSeedData.requests,
      logs: parsed.logs || initialSeedData.logs,
      companySettings: parsed.companySettings || initialSeedData.companySettings,
    };
  } catch (e) {
    console.error('Failed to parse localStorage data', e);
    return initialSeedData;
  }
}

export function saveStorageData(data: StorageData) {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
    window.dispatchEvent(new Event('aec_storage_updated'));
  } catch (e) {
    console.error('Failed to save data to localStorage', e);
  }
}

export function resetStorageData() {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(initialSeedData));
  window.dispatchEvent(new Event('aec_storage_updated'));
  return initialSeedData;
}
