"""initial schema

Revision ID: 552c0ab0a142
Revises: 
Create Date: 2026-08-17 00:30:20.040046

"""
from alembic import op
import sqlalchemy as sa
from app.models.mixins import UTCDateTime


# revision identifiers, used by Alembic.
revision = '552c0ab0a142'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proponents',
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=50), nullable=True),
    sa.Column('project_type', sa.Enum('Cold storage', 'Mining and quarry', 'Gold mining', 'Sand mining', 'Construction', 'Hotel', 'Factory', 'Warehouse', 'Exploration', 'Logging', 'Other', name='project_type'), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('project_location', sa.String(length=255), nullable=True),
    sa.Column('project_description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Inactive', name='proponent_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proponents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proponents_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_proponents_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_proponents_status'), ['status'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('admin', 'user', 'client', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('proponent_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proponent_id'], ['proponents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_proponent_id'), ['proponent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('audit_logs',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index('ix_audit_logs_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index('ix_audit_logs_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('bookings',
    sa.Column('proponent_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=50), nullable=True),
    sa.Column('service_needed', sa.Enum('Free consultation call', 'Environmental audit planning session', 'Biannual monitoring planning session', 'Quarterly monitoring planning session', 'ESIA/EMP/EPB consultation', 'Mining license support session', 'Compliance review session', 'Report planning session', 'Site visit planning call', 'Corrective action support session', name='booking_service'), nullable=False),
    sa.Column('preferred_date', sa.Date(), nullable=True),
    sa.Column('preferred_time', sa.String(length=20), nullable=True),
    sa.Column('project_location', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('booking_status', sa.Enum('Pending', 'Confirmed', 'Completed', 'Rescheduled', 'Cancelled', name='booking_status'), nullable=False),
    sa.Column('meeting_link', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proponent_id'], ['proponents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_booking_status'), ['booking_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_proponent_id'), ['proponent_id'], unique=False)

    op.create_table('company_settings',
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('company_email', sa.String(length=320), nullable=False),
    sa.Column('company_phone', sa.String(length=50), nullable=True),
    sa.Column('company_whatsapp', sa.String(length=50), nullable=True),
    sa.Column('company_address', sa.String(length=255), nullable=True),
    sa.Column('company_tagline', sa.String(length=255), nullable=True),
    sa.Column('enable_email_notifications', sa.Boolean(), nullable=False),
    sa.Column('enable_whatsapp_notifications', sa.Boolean(), nullable=False),
    sa.Column('reminder_30_enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder_14_enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder_7_enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder_1_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_settings_updated_by'), ['updated_by'], unique=False)

    op.create_table('files',
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.Enum('permit', 'evidence', 'report', 'avatar', 'other', name='file_category'), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_stored_name'), ['stored_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_files_uploaded_by'), ['uploaded_by'], unique=False)

    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('notification_type', sa.Enum('Report reminder', 'Overdue notice', 'Findings notice', 'Evidence submission', 'Evidence review', 'Booking confirmation', 'Service request', 'Corrective action', 'Support Request', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_notification_type'), ['notification_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_notifications_user_read', ['user_id', 'is_read'], unique=False)

    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('used_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('service_requests',
    sa.Column('proponent_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=50), nullable=True),
    sa.Column('service_needed', sa.Enum('Environmental Audit Report', 'Biannual Monitoring Report', 'Quarterly Monitoring Report', 'Environmental and Social Impact Assessment', 'Environmental Management Plan', 'Environmental Project Brief', 'Mining license support', 'Compliance advisory', 'Environmental monitoring', 'Corrective action tracking', 'Other', name='request_service'), nullable=False),
    sa.Column('project_location', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('New', 'Contacted', 'In Review', 'In progress', 'Completed', 'Closed', 'Archived', name='request_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proponent_id'], ['proponents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_requests_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_requests_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_requests_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_requests_proponent_id'), ['proponent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_requests_status'), ['status'], unique=False)

    op.create_table('permits',
    sa.Column('proponent_id', sa.Uuid(), nullable=False),
    sa.Column('permit_number', sa.String(length=50), nullable=False),
    sa.Column('permit_type', sa.Enum('EPA Environmental Permit', 'Mining License', 'Environmental Impact License', 'Waste Management Permit', 'Other', name='permit_type'), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Expired', 'Suspended', 'Pending Renewal', name='permit_status'), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('file_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proponent_id'], ['proponents.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permits_expiry_date'), ['expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_permits_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_permits_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_permits_permit_number'), ['permit_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_permits_proponent_id'), ['proponent_id'], unique=False)
        batch_op.create_index('ix_permits_proponent_status', ['proponent_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_permits_status'), ['status'], unique=False)

    op.create_table('report_schedules',
    sa.Column('proponent_id', sa.Uuid(), nullable=False),
    sa.Column('permit_id', sa.Uuid(), nullable=True),
    sa.Column('report_type', sa.Enum('Environmental Audit Report', 'Biannual Monitoring Report', 'Quarterly Monitoring Report', name='report_type'), nullable=False),
    sa.Column('reporting_period', sa.String(length=100), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Submitted', 'Overdue', 'Completed', name='report_status'), nullable=False),
    sa.Column('submitted_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('reminder_30_sent', sa.Boolean(), nullable=False),
    sa.Column('reminder_14_sent', sa.Boolean(), nullable=False),
    sa.Column('reminder_7_sent', sa.Boolean(), nullable=False),
    sa.Column('reminder_1_sent', sa.Boolean(), nullable=False),
    sa.Column('reminder_due_sent', sa.Boolean(), nullable=False),
    sa.Column('reminder_overdue_sent', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['permit_id'], ['permits.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proponent_id'], ['proponents.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_schedules_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_schedules_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_schedules_permit_id'), ['permit_id'], unique=False)
        batch_op.create_index('ix_report_schedules_proponent_due', ['proponent_id', 'due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_schedules_proponent_id'), ['proponent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_schedules_status'), ['status'], unique=False)

    op.create_table('findings',
    sa.Column('proponent_id', sa.Uuid(), nullable=False),
    sa.Column('report_schedule_id', sa.Uuid(), nullable=True),
    sa.Column('inspection_area', sa.String(length=150), nullable=True),
    sa.Column('finding_title', sa.String(length=255), nullable=False),
    sa.Column('finding_description', sa.Text(), nullable=True),
    sa.Column('compliance_status', sa.Enum('Compliant', 'Non-compliant', 'Requires improvement', 'Pending review', 'Observation', 'Minor non-compliance', 'Major non-compliance', 'Improvement needed', name='compliance_status'), nullable=False),
    sa.Column('risk_level', sa.Enum('Low', 'Medium', 'High', name='risk_level'), nullable=False),
    sa.Column('corrective_action', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('action_deadline', sa.Date(), nullable=True),
    sa.Column('responsible_party', sa.String(length=150), nullable=True),
    sa.Column('action_status', sa.Enum('Open', 'Pending', 'In progress', 'Submitted for review', 'Verified', 'Overdue', name='action_status'), nullable=False),
    sa.Column('sent_to_proponent', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['proponent_id'], ['proponents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['report_schedule_id'], ['report_schedules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_action_deadline'), ['action_deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_action_status'), ['action_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_compliance_status'), ['compliance_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index('ix_findings_proponent_action_status', ['proponent_id', 'action_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_proponent_id'), ['proponent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_report_schedule_id'), ['report_schedule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_risk_level'), ['risk_level'], unique=False)

    op.create_table('evidence',
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('proponent_id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=True),
    sa.Column('reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('evidence_title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('review_status', sa.Enum('Pending review', 'Approved', 'Rejected', 'More action needed', name='review_status'), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('admin_comment', sa.Text(), nullable=True),
    sa.Column('submitted_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['proponent_id'], ['proponents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index('ix_evidence_finding_review_status', ['finding_id', 'review_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_proponent_id'), ['proponent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_review_status'), ['review_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_reviewer_id'), ['reviewer_id'], unique=False)

    op.create_table('notification_logs',
    sa.Column('proponent_id', sa.Uuid(), nullable=True),
    sa.Column('report_schedule_id', sa.Uuid(), nullable=True),
    sa.Column('finding_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.Enum('Email', 'WhatsApp', name='notification_channel'), nullable=False),
    sa.Column('notification_type', sa.Enum('Report reminder', 'Overdue notice', 'Findings notice', 'Evidence submission', 'Evidence review', 'Booking confirmation', 'Service request', 'Corrective action', 'Support Request', name='notification_type'), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('message_body', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('Pending', 'Sent', 'Failed', name='notification_log_status'), nullable=False),
    sa.Column('sent_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proponent_id'], ['proponents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_schedule_id'], ['report_schedules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.create_index('ix_notification_logs_channel_status', ['channel', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index('ix_notification_logs_proponent_created', ['proponent_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_proponent_id'), ['proponent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_recipient'), ['recipient'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_report_schedule_id'), ['report_schedule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_logs_status'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_report_schedule_id'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_recipient'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_proponent_id'))
        batch_op.drop_index('ix_notification_logs_proponent_created')
        batch_op.drop_index(batch_op.f('ix_notification_logs_finding_id'))
        batch_op.drop_index('ix_notification_logs_channel_status')

    op.drop_table('notification_logs')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_reviewer_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_review_status'))
        batch_op.drop_index(batch_op.f('ix_evidence_proponent_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_is_deleted'))
        batch_op.drop_index('ix_evidence_finding_review_status')
        batch_op.drop_index(batch_op.f('ix_evidence_finding_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_file_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_risk_level'))
        batch_op.drop_index(batch_op.f('ix_findings_report_schedule_id'))
        batch_op.drop_index(batch_op.f('ix_findings_proponent_id'))
        batch_op.drop_index('ix_findings_proponent_action_status')
        batch_op.drop_index(batch_op.f('ix_findings_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_findings_compliance_status'))
        batch_op.drop_index(batch_op.f('ix_findings_action_status'))
        batch_op.drop_index(batch_op.f('ix_findings_action_deadline'))

    op.drop_table('findings')
    with op.batch_alter_table('report_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_schedules_status'))
        batch_op.drop_index(batch_op.f('ix_report_schedules_proponent_id'))
        batch_op.drop_index('ix_report_schedules_proponent_due')
        batch_op.drop_index(batch_op.f('ix_report_schedules_permit_id'))
        batch_op.drop_index(batch_op.f('ix_report_schedules_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_report_schedules_due_date'))

    op.drop_table('report_schedules')
    with op.batch_alter_table('permits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permits_status'))
        batch_op.drop_index('ix_permits_proponent_status')
        batch_op.drop_index(batch_op.f('ix_permits_proponent_id'))
        batch_op.drop_index(batch_op.f('ix_permits_permit_number'))
        batch_op.drop_index(batch_op.f('ix_permits_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_permits_file_id'))
        batch_op.drop_index(batch_op.f('ix_permits_expiry_date'))

    op.drop_table('permits')
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_requests_status'))
        batch_op.drop_index(batch_op.f('ix_service_requests_proponent_id'))
        batch_op.drop_index(batch_op.f('ix_service_requests_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_service_requests_email'))
        batch_op.drop_index(batch_op.f('ix_service_requests_created_by'))

    op.drop_table('service_requests')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_expires_at'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_read')
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_notification_type'))

    op.drop_table('notifications')
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_uploaded_by'))
        batch_op.drop_index(batch_op.f('ix_files_stored_name'))
        batch_op.drop_index(batch_op.f('ix_files_category'))

    op.drop_table('files')
    with op.batch_alter_table('company_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_settings_updated_by'))

    op.drop_table('company_settings')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_proponent_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_bookings_email'))
        batch_op.drop_index(batch_op.f('ix_bookings_created_by'))
        batch_op.drop_index(batch_op.f('ix_bookings_booking_status'))

    op.drop_table('bookings')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index('ix_audit_logs_user_created')
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index('ix_audit_logs_entity')
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_proponent_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('proponents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proponents_status'))
        batch_op.drop_index(batch_op.f('ix_proponents_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_proponents_email'))

    op.drop_table('proponents')
    # ### end Alembic commands ###
