"""add auth fields and token blocklist

Revision ID: c8187b3b3669
Revises: 552c0ab0a142
Create Date: 2026-08-17 14:55:30.711700

"""
from alembic import op
import sqlalchemy as sa
from app.models.mixins import UTCDateTime


# revision identifiers, used by Alembic.
revision = 'c8187b3b3669'
down_revision = '552c0ab0a142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blocklist',
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('token_type', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('expires_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_blocklist_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_token_blocklist_jti'), ['jti'], unique=True)
        batch_op.create_index('ix_token_blocklist_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_token_blocklist_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_at', UTCDateTime(timezone=True), nullable=True))
        # token_version must be NOT NULL; backfill existing rows with 0, then
        # drop the server default so future inserts rely on the ORM default.
        batch_op.add_column(sa.Column('token_version', sa.Integer(), nullable=False, server_default=sa.text('0')))
        batch_op.alter_column('token_version', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('token_version')
        batch_op.drop_column('last_login_at')

    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blocklist_user_id'))
        batch_op.drop_index('ix_token_blocklist_user_created')
        batch_op.drop_index(batch_op.f('ix_token_blocklist_jti'))
        batch_op.drop_index(batch_op.f('ix_token_blocklist_expires_at'))

    op.drop_table('token_blocklist')
    # ### end Alembic commands ###
